# Generated by Django 3.2.7 on 2021-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book_id',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
