# Generated by Django 3.2.7 on 2021-10-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_order_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Book',
            new_name='book',
        ),
    ]
