# Generated by Django 3.2.7 on 2021-10-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_auto_20211012_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
