# Generated by Django 3.2.7 on 2021-09-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
