# Generated by Django 3.2.7 on 2021-09-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_book_details_language_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_book_no', models.IntegerField()),
                ('stock_availability', models.BooleanField(default=True)),
                ('book_details_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.book_details')),
            ],
        ),
    ]
