# Generated by Django 3.2.7 on 2021-10-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_auto_20210925_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='natinality',
            options={'verbose_name': 'Natinality', 'verbose_name_plural': 'Natinalities'},
        ),
    ]
