# Generated by Django 3.2.7 on 2021-10-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_auto_20211006_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='natinality',
            new_name='nationality',
        ),
    ]
