# Generated by Django 3.2.7 on 2021-09-30 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0011_auto_20210925_1524'),
        ('user', '0002_auto_20210930_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.book'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
