# Generated by Django 3.2.7 on 2021-10-06 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30, null=True)),
                ('profession', models.CharField(default='', max_length=50, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('facebook_profile', models.CharField(max_length=120, null=True)),
                ('national_id_no', models.IntegerField()),
                ('addr_District', models.CharField(max_length=40, null=True)),
                ('addr_thana', models.CharField(max_length=40, null=True)),
                ('postcode', models.IntegerField(null=True)),
                ('word_no', models.IntegerField(null=True)),
                ('house_no', models.IntegerField(blank=True, null=True)),
                ('acc_creation_date', models.DateField(auto_now_add=True, null=True)),
                ('addr_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
