# Generated by Django 3.2.7 on 2021-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_division_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_id_no',
            field=models.IntegerField(null=True),
        ),
    ]
