# Generated by Django 3.2.7 on 2021-10-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_member_library_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, default='d_image.jpeg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
