# Generated by Django 3.2.7 on 2021-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211009_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_id_no',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
